### ISSUE TITLE
PlutoGrideMode.Select | Enter key Pressed

### ISSUE THREAD

**Issue by NiranjanShah** [bosskmk/pluto_grid#185]
Following error is generated when PlutoGrid **mode is in PlutoGridMode.select** and when enter is pressed on any of the cell.

Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:62892/dart_sdk.js:5333:11)
    at Object.nullCheck (http://localhost:62892/dart_sdk.js:5666:30)
    at pluto_grid_key_manager.PlutoGridKeyManager.new.[_handleEnter] (http://localhost:62892/packages/pluto_grid/src/ui/pluto_right_frozen_rows.dart.lib.js:18592:14)
    at pluto_grid_key_manager.PlutoGridKeyManager.new.[_handler] (http://localhost:62892/packages/pluto_grid/src/ui/pluto_right_frozen_rows.dart.lib.js:18489:29)
    at _RootZone.runUnaryGuarded (http://localhost:62892/dart_sdk.js:38814:11)
    at _BroadcastSubscription.new.[_sendData] (http://localhost:62892/dart_sdk.js:32431:22)
    at _DelayedData.new.perform (http://localhost:62892/dart_sdk.js:35846:28)
    at _StreamImplEvents.new.handleNext (http://localhost:62892/dart_sdk.js:35956:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:62892/dart_sdk.js:35708:16)
    at Object._microtaskLoop (http://localhost:62892/dart_sdk.js:39175:13)
    at _startMicrotaskLoop (http://localhost:62892/dart_sdk.js:39181:13)
    at http://localhost:62892/dart_sdk.js:34688:9

**Comment by bosskmk** [comment]
The example below runs in Select mode.
But no error occurred.

Could you please provide a minimal code to reproduce the error?

Also, what about your flutter and dart versions?

https://weblaze.dev/pluto_grid/build/web/#feature/listing-mode
