### ISSUE TITLE
Pasting Excel Document Text

### ISSUE THREAD

**Issue by caymanmckee** [bosskmk/pluto_grid#320]
When pasting an excel document into the editable table, I get am getting this error:

[+2931 ms] Error: RangeError (index): Index out of range: index should be less than 1: 1
               at Object.throw_ [as throw] (http://localhost:55719/dart_sdk.js:5374:11)
               at Array.[dartx._get] (http://localhost:55719/dart_sdk.js:17237:21)
               at pluto_grid_state_manager.PlutoGridStateManager.new.[_pasteCellValueInOrder] (http://localhost:55719/packages/pluto_grid/src/ui/pluto_right_frozen_rows.dart.lib.js:12981:64)
               at pluto_grid_state_manager.PlutoGridStateManager.new.pasteCellValue (http://localhost:55719/packages/pluto_grid/src/ui/pluto_right_frozen_rows.dart.lib.js:12885:40)
               at http://localhost:55719/packages/pluto_grid/src/ui/pluto_right_frozen_rows.dart.lib.js:14591:27
               at _RootZone.runUnary (http://localhost:55719/dart_sdk.js:40503:58)
               at _FutureListener.then.handleValue (http://localhost:55719/dart_sdk.js:35432:29)
               at handleValueCallback (http://localhost:55719/dart_sdk.js:36017:49)
               at Function._propagateToListeners (http://localhost:55719/dart_sdk.js:36055:17)
               at _Future.new.[_completeWithValue] (http://localhost:55719/dart_sdk.js:35897:23)
               at async._AsyncCallbackEntry.new.callback (http://localhost:55719/dart_sdk.js:35920:35)
               at Object._microtaskLoop (http://localhost:55719/dart_sdk.js:40808:13)
               at _startMicrotaskLoop (http://localhost:55719/dart_sdk.js:40814:13)
               at http://localhost:55719/dart_sdk.js:36279:9

I have tried changing the number of rows and the amount that I past in. As well as freezing and unfreezing rows and columns. Nothing seems to help

**Comment by bosskmk** [comment]
May I know your flutter version and PlutoGrid version?
I don't have excel and couldn't reproduce the error when copying and pasting from google sheets.
I need more explanation so I can reproduce the error.
