### ISSUE TITLE
ScrollController issue

### ISSUE THREAD

**Issue by kevansaba-operium** [bosskmk/pluto_grid#366]
Hello,

First of all, thank you for this awesome package! I am running into a weird error when trying to refresh my `PlutoGrid` (see stack trace at the bottom of this post). 

Basically, I have a controller class that holds the state (a `GetxController`), and upon a `onRowsMoved`, I am running a bit of logic to update the state in my controller and calling GetX update function to rebuild a `GetBuilder` which has my `PlutoGrid` has its child and unique widget key. I know it's not the most resource savvy way of doing things, but I can't wrap my head around the reason why this fails. Any ideas?

By the way, I tried a similar logic on `onChanged` and it seems to work without any issues...

Thanks in advance,
Kevan

```
Error: Assertion failed:
../…/lib/linked_scroll_controller.dart:34
_attachedControllers.isNotEmpty
"LinkedScrollControllerGroup does not have any scroll controllers attached."
    at Object.throw_ [as throw] (http://localhost:59655/dart_sdk.js:5063:11)
    at Object.assertFailed (http://localhost:59655/dart_sdk.js:4988:15)
at linked_scroll_controller.LinkedScrollControllerGroup.new.get offset [as offset] (http://localhost:59655/packages/linked_scroll_controller/linked_scroll_controller.dart.lib.js:69:58)
at pluto_grid_scroll_update_event.PlutoGridScrollUpdateEvent.new.[_scroll] (http://localhost:59655/packages/pluto_grid/src/ui/pluto_right_frozen_rows.dart.lib.js:16458:31)
at pluto_grid_scroll_update_event.PlutoGridScrollUpdateEvent.new.handler (http://localhost:59655/packages/pluto_grid/src/ui/pluto_right_frozen_rows.dart.lib.js:16450:27)
at pluto_grid_event_manager.PlutoGridEventManager.new.[_handler] (http://localhost:59655/packages/pluto_grid/src/ui/pluto_right_frozen_rows.dart.lib.js:16370:13)
    at _RootZone.runUnaryGuarded (http://localhost:59655/dart_sdk.js:39999:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:59655/dart_sdk.js:33524:22)
    at _ControllerSubscription.new.[_add] (http://localhost:59655/dart_sdk.js:33473:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:59655/dart_sdk.js:36489:34)
    at _SyncStreamController.new.[_sendData] (http://localhost:59655/dart_sdk.js:36599:32)
    at _SyncStreamController.new.[_add] (http://localhost:59655/dart_sdk.js:36302:26)
    at _SyncStreamController.new.add (http://localhost:59655/dart_sdk.js:36268:19)
    at _RootZone.runUnaryGuarded (http://localhost:59655/dart_sdk.js:39999:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:59655/dart_sdk.js:33524:22)
    at _ControllerSubscription.new.[_add] (http://localhost:59655/dart_sdk.js:33473:26)
    at _MultiStreamController.new.addSync (http://localhost:59655/dart_sdk.js:37672:56)
at _MultiControllerSink.new.add (http://localhost:59655/packages/rxdart/src/utils/forwarding_stream.dart.lib.js:32:32)
at _BackpressureStreamSink.new.resolveWindowEnd (http://localhost:59655/packages/rxdart/src/transformers/backpressure/backpressure.dart.lib.js:221:18)
at http://localhost:59655/packages/rxdart/src/transformers/backpressure/backpressure.dart.lib.js:192:133
    at _RootZone.runGuarded (http://localhost:59655/dart_sdk.js:39983:11)
    at sendDone (http://localhost:59655/dart_sdk.js:33566:24)
    at _StateStreamSubscription.new.[_sendDone] (http://localhost:59655/dart_sdk.js:33576:11)
    at _StateStreamSubscription.new.[_close] (http://localhost:59655/dart_sdk.js:33491:26)
    at _TakeStream.new.[_handleData] (http://localhost:59655/dart_sdk.js:38064:25)
    at _StateStreamSubscription.new.[_handleData] (http://localhost:59655/dart_sdk.js:37799:37)
    at _RootZone.runUnaryGuarded (http://localhost:59655/dart_sdk.js:39999:11)
    at _ControllerSubscription.new.[_sendData] (http://localhost:59655/dart_sdk.js:33524:22)
    at _ControllerSubscription.new.[_add] (http://localhost:59655/dart_sdk.js:33473:26)
    at _SyncStreamController.new.[_sendData] (http://localhost:59655/dart_sdk.js:36489:34)
    at _SyncStreamController.new.[_sendData] (http://localhost:59655/dart_sdk.js:36599:32)
    at _SyncStreamController.new.[_add] (http://localhost:59655/dart_sdk.js:36302:26)
    at _SyncStreamController.new.add (http://localhost:59655/dart_sdk.js:36268:19)
at http://localhost:59655/packages/rxdart/src/streams/timer.dart.lib.js:59:34
    at internalCallback (http://localhost:59655/dart_sdk.js:26215:11)
Restarted application in 619ms.

```

**Comment by bosskmk** [comment]
I'm not sure about the content of the issue.
Could you please provide your version of flutter, PlutoGrid and the minimum code I can get to reproduce that error?

**Comment by kevansaba-operium** [comment]
I upgraded from PlutoGrid v2.8.0 to v2.9.1 and the problem disappeared... I will close this one.
