### ISSUE TITLE
Can this package create an excel like sheet that can scroll programatically?

### ISSUE THREAD

**Issue by fenchai23** [bosskmk/pluto_grid#446]
I have been wanting to create an excel like sheet but also being able to scroll to a cell I want to search just like excel does.

more details here https://stackoverflow.com/questions/72399829/how-can-i-create-an-excel-like-sheet-with-flutter-widgets?noredirect=1#comment127905020_72399829

is this possible?

**Comment by bosskmk** [comment]
@fenchai23 

Any function you want is available.
However, it can be slow in Dev mode if you have a lot of rows.
To measure performance, test in Build mode.

**Comment by fenchai23** [comment]
> @fenchai23 
> 
> Any function you want is available.
> However, it can be slow in Dev mode if you have a lot of rows.
> To measure performance, test in Build mode.

do you have any example that uses the function to scroll programatically to a cell? I would really like to test it.

**Comment by bosskmk** [comment]
@fenchai23 
Check out the two links below.

StateManager access
https://github.com/bosskmk/pluto_grid/wiki/pluto-state-manager-for-english

Scroll related methods
https://github.com/bosskmk/pluto_grid/blob/master/lib/src/manager/state/scroll_state.dart

**Comment by fenchai23** [comment]
@bosskmk 

I can't believe my eyes, your package really does it all...! I am glad someone recommended this package to me.

there are still some questions I want to ask about, please mind that I am still using v1.1.0 because I have yet to migrate to null safety.

- Is there a way to hide or remove the header row? it is useless for my project.
- How does moveByCol or moveByRow work? and why does PlutoMoveDirection matter? if I am moving by Column why can I use vertical PlutoMoveDirection? it makes no sense to me.
At the moment, I am using it this way because it is the most consistent way.

```
// scroll to 0,0 first (because of PlutoMoveDirection)
    plutoStateManager.moveScrollByColumn(PlutoMoveDirection.right, 0);
    plutoStateManager.moveScrollByRow(PlutoMoveDirection.down, 0);

// scroll to target item (do directions matter?)
    plutoStateManager.moveScrollByColumn(
        PlutoMoveDirection.right, itemPos.columnIdx);
    plutoStateManager.moveScrollByRow(PlutoMoveDirection.down, itemPos.rowIdx);
```

Does moving it this way scroll until cell is on the center of the screen? How do I make it so that cell is on the top left?

**Comment by bosskmk** [comment]
There is no function to hide the subject area of a column.
It may be added in the future.

`PlutoMoveDirection` is required to receive the direction when moving with the direction keys on the keyboard, check whether it is possible to move, and calculate where and how much to move the scroll according to the moving direction.
The logic to move the scroll according to the direction keys is the logic in the early stages of development.
It would be possible to change the logic to move to a specific cell even if there is no direction.

Moving to the top left or the end of the grid is possible using two methods: `moveCurrentCellToEdgeOfRows` and `moveCurrentCellToEdgeOfColumns`.
Shortcut keys are `Home`, `End`, `Ctrl + Home`, `Ctrl + End`.

**Comment by fenchai23** [comment]
@bosskmk 

sorry, I think I did not explain well with my statement 
> How do I make it so that cell is on the top left?
Let me explain, when I search for a cell value, this is what I use:

**Comment by bosskmk** [comment]
@fenchai23 
I made an example.
It may not be perfect.
For example, if there is a column group, there is no footer, etc...
The code also needs to be neatly organized.
Try this out and you're done.
And please leave the finished code in the comments.
I can deploy the feature to the next version.

```dart
enum ScrollDirection {
  leftTop,
  rightTop,
  leftBottom,
  rightBottom,
}

class _EmptyScreenState extends State<EmptyScreen> {
  late List<PlutoColumn> columns;

  late List<PlutoRow> rows;

  late PlutoGridStateManager stateManager;

  @override
  void initState() {
    super.initState();

    columns = [
      PlutoColumn(
        title: 'column1',
        field: 'column1',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column2',
        field: 'column2',
        type: PlutoColumnType.text(),
      ),
      PlutoColumn(
        title: 'column3',
        field: 'column3',
        type: PlutoColumnType.text(),
      ),
      ...DummyData(30, 0).columns,
    ];

    rows = DummyData.rowsByColumns(length: 100, columns: columns);
  }

  void scrollToEdgeOnDisplayArea(
    ScrollDirection direction,
  ) {
    final cellPosition = stateManager.currentCellPosition;

    if (cellPosition == null) {
      return;
    }

    double x = 0;
    double y = 0;

    switch (direction) {
      case ScrollDirection.leftTop:
        x = stateManager
            .bodyColumnsWidthAtColumnIdx(cellPosition.columnIdx! - 1);

        y = cellPosition.rowIdx! * stateManager.rowTotalHeight;

        break;
      case ScrollDirection.rightTop:
        x = stateManager
                .bodyColumnsWidthAtColumnIdx(cellPosition.columnIdx! + 1) -
            stateManager.bodyRightScrollOffset +
            PlutoGridSettings.offsetScrollingFromEdge;

        y = cellPosition.rowIdx! * stateManager.rowTotalHeight;

        break;
      case ScrollDirection.leftBottom:
        x = stateManager
            .bodyColumnsWidthAtColumnIdx(cellPosition.columnIdx! - 1);

        y = (cellPosition.rowIdx! + 1) * stateManager.rowTotalHeight -
            stateManager.bodyDownScrollOffset +
            PlutoGridSettings.offsetScrollingFromEdge +
            stateManager.footerHeight;
        break;
      case ScrollDirection.rightBottom:
        x = stateManager
                .bodyColumnsWidthAtColumnIdx(cellPosition.columnIdx! + 1) -
            stateManager.bodyRightScrollOffset +
            PlutoGridSettings.offsetScrollingFromEdge;

        y = (cellPosition.rowIdx! + 1) * stateManager.rowTotalHeight -
            stateManager.bodyDownScrollOffset +
            PlutoGridSettings.offsetScrollingFromEdge +
            stateManager.footerHeight;
        break;
    }

    if (x < 0) {
      x = 0;
    }

    if (y < 0) {
      y = 0;
    }

    if (x > stateManager.scroll!.maxScrollHorizontal) {
      x = stateManager.scroll!.maxScrollHorizontal;
    }

    if (y > stateManager.scroll!.maxScrollVertical) {
      y = stateManager.scroll!.maxScrollVertical;
    }

    stateManager.scroll!.bodyRowsHorizontal!.jumpTo(x);
    stateManager.scroll!.bodyRowsVertical!.jumpTo(y);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        padding: const EdgeInsets.all(15),
        child: PlutoGrid(
          columns: columns,
          rows: rows,
          onChanged: (PlutoGridOnChangedEvent event) {
            print(event);
          },
          onLoaded: (PlutoGridOnLoadedEvent event) {
            stateManager = event.stateManager;
          },
          createFooter: (PlutoGridStateManager stateManager) {
            return SizedBox(
              height: 45,
              child: Row(
                children: [
                  TextButton(
                    child: const Text('leftTop'),
                    onPressed: () {
                      scrollToEdgeOnDisplayArea(
                        ScrollDirection.leftTop,
                      );
                    },
                  ),
                  TextButton(
                    child: const Text('rightTop'),
                    onPressed: () {
                      scrollToEdgeOnDisplayArea(
                        ScrollDirection.rightTop,
                      );
                    },
                  ),
                  TextButton(
                    child: const Text('leftBottom'),
                    onPressed: () {
                      scrollToEdgeOnDisplayArea(
                        ScrollDirection.leftBottom,
                      );
                    },
                  ),
                  TextButton(
                    child: const Text('rightBottom'),
                    onPressed: () {
                      scrollToEdgeOnDisplayArea(
                        ScrollDirection.rightBottom,
                      );
                    },
                  ),
                ],
              ),
            );
          },
          configuration: const PlutoGridConfiguration(),
        ),
      ),
    );
  }
}
```

**Comment by fenchai23** [comment]
@bosskmk 

This is my current code to scroll to a cell:
```dart
void scrollToItem(
    Key itemKey,
  ) {
    // scroll to 0,0 first (because of PlutoMoveDirection)
    stateManager.moveScrollByColumn(PlutoMoveDirection.right, -1);
    stateManager.moveScrollByRow(PlutoMoveDirection.down, -1);

    // get item pos
    final PlutoGridCellPosition itemPos =
        stateManager.cellPositionByCellKey(itemKey);

    // get item PlutoCell
    final PlutoCell cell = stateManager.rows[itemPos.rowIdx].cells.entries
        .elementAt(itemPos.columnIdx)
        .value;

    // set current cell selection
    stateManager.setCurrentCell(cell, itemPos.columnIdx);

    // scroll to target item (do directions matter?)
    stateManager.moveScrollByColumn(
        PlutoMoveDirection.right, itemPos.columnIdx);
    stateManager.moveScrollByRow(PlutoMoveDirection.down, itemPos.rowIdx);

    scrollToEdgeOnDisplayArea(ScrollDirection.leftTop);
  }
```

This is what happens when I try to run with my current code programmatically (no idea why it gives me error):
```
E/flutter (24399): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method '-' was called on null.
E/flutter (24399): Receiver: null
E/flutter (24399): Tried calling: -(1)
E/flutter (24399): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (24399): #1      InventoryMapDataController.scrollToEdgeOnDisplayArea
E/flutter (24399): #2      InventoryMapDataController.scrollToItem
E/flutter (24399): #3      InventoryMapDataController.findItemInMap
E/flutter (24399): #4      InvoiceDetails.showInvoiceDetailsMap.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>
E/flutter (24399): <asynchronous suspension>
E/flutter (24399): #5      InvoiceDetails.showInvoiceDetailsMap.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:hyl/screens/pages/catalogPageTree/pages/uploadedInvoicesPage/uploadedInvoicesPage.dart)
E/flutter (24399): #6      _InkResponseState._handleTap
E/flutter (24399): #7      _InkResponseState.build.<anonymous closure>
E/flutter (24399): #8      GestureRecognizer.invokeCallback
E/flutter (24399): #9      TapGestureRecognizer.handleTapUp
E/flutter (24399): #10     BaseTapGestureRecognizer._checkUp
E/flutter (24399): #11     BaseTapGestureRecognizer.acceptGesture
E/flutter (24399): #12     GestureArenaManager.sweep
E/flutter (24399): #13     GestureBinding.handleEvent
E/flutter (24399): #14     GestureBinding.dispatchEvent
E/flutter (24399): #15     RendererBinding.dispatchEvent
E/flutter (24399): #16     GestureBinding._handlePointerEvent
E/flutter (24399): #17     GestureBinding._flushPointerEventQueue
E/flutter (24399): #18     GestureBinding._handlePointerDataPacket
E/flutter (24399): #19     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (24399): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (24399): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (24399): #22     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (24399): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (24399):

```

And this is the result when I click on the footer actions:

https://user-images.githubusercontent.com/52770796/172748636-4eb3db5b-f350-465e-b59b-7bb25e80c8bf.mp4

btw do you have any idea on how to improve performance? my data is only 54 columns and about 100 rows but the scrolling is pretty bad, it lags when scrolling left and right but it is really but really slow when scrolling up and down, it is slower on my Galaxy S21 than on debug mode in my android emulator.

thanks!

**Comment by bosskmk** [comment]
@fenchai23 
Slow in profile or release mode?

**Comment by bosskmk** [comment]
@fenchai23 
I don't have an Android device, so I can only test on the emulator.

In my case it outputted 10,000,000 cells total with 1,000 columns and 10,000 rows, which did not slow down when scrolling.

If possible, please check the performance test in profile mode.

If it's still slow, check the Performance and CPU Debug tools.

**Comment by fenchai23** [comment]
> @fenchai23 
> I don't have an Android device, so I can only test on the emulator.
> 
> In my case it outputted 10,000,000 cells total with 1,000 columns and 10,000 rows, which did not slow down when scrolling.
> 
> If possible, please check the performance test in profile mode.
> 
> If it's still slow, check the Performance and CPU Debug tools.

I have the app running downloaded from playstore, I believe the build is profile mode?

do you have an example of performance with thousands of rows? maybe are you willing to test an example I make?

**Comment by bosskmk** [comment]
Execution is simple. Just create columns and rows as in the link below.

https://github.com/bosskmk/pluto_grid/blob/master/demo/lib/screen/empty_screen.dart

However, if many columns and rows are created before PlutoGrid is created, UI freezing may occur regardless of PlutoGrid execution. In this case, please refer to the link below.

https://github.com/bosskmk/pluto_grid/blob/master/demo/lib/screen/feature/add_rows_asynchronously.dart

**Comment by bosskmk** [comment]
The example below was run on the Android emulator Pixel 4 API 30 .
It is executed with the attached source code and outputs 1,000 columns and 10,000 rows.
Scrolling up and down is much faster, but scrolling left and right isn't annoying enough.
Of course, this will need to be improved like scrolling up and down.

https://user-images.githubusercontent.com/5284141/173157165-6370ead1-6202-4657-baeb-74a942a373e5.mp4

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';

import '../../dummy_data/development.dart';
import '../../widget/pluto_example_button.dart';
import '../../widget/pluto_example_screen.dart';

class AddRowsAsynchronouslyScreen extends StatefulWidget {
  static const routeName = 'feature/add-rows-asynchronously';

  const AddRowsAsynchronouslyScreen({Key? key}) : super(key: key);

  @override
  _AddRowsAsynchronouslyScreenState createState() =>
      _AddRowsAsynchronouslyScreenState();
}

class _AddRowsAsynchronouslyScreenState
    extends State<AddRowsAsynchronouslyScreen> {
  final List<PlutoColumn> columns = [];

  final List<PlutoRow> rows = [];

  late PlutoGridStateManager stateManager;

  @override
  void initState() {
    super.initState();

    /// Columns must be provided at the beginning of a row synchronously.
    columns.addAll(DummyData(1000, 0).columns);

    fetchRows().then((fetchedRows) {
      /// When there are many rows and the UI freezes when the grid is loaded
      /// Initialize the rows asynchronously through the initializeRowsAsync method
      /// Add rows to stateManager.refRows.
      /// And disable the loading screen.
      PlutoGridStateManager.initializeRowsAsync(
        columns,
        fetchedRows,
      ).then((value) {
        stateManager.refRows.addAll(FilteredList(initialList: value));

        /// In this example,
        /// the loading screen is activated in the onLoaded callback when the grid is created.
        /// If the loading screen is not activated
        /// You must update the grid state by calling the stateManager.notifyListeners() method.
        /// Because calling setShowLoading updates the grid state
        /// No need to call stateManager.notifyListeners.
        stateManager.setShowLoading(false);
      });
    });
  }

  /// This method creates rows asynchronously for the sake of example.
  /// In actual use, you are requesting server-side data with Http and
  /// You will need to create and return PlutoRow and PlutoCell.
  /// It's up to you.
  /// This is just an example.
  Future<List<PlutoRow>> fetchRows() {
    final Completer<List<PlutoRow>> completer = Completer();

    final List<PlutoRow> _rows = [];

    int count = 0;

    const max = 100;

    const chunkSize = 100;

    const totalRows = chunkSize * max;

    Timer.periodic(const Duration(milliseconds: 1), (timer) {
      if (count == max) {
        return;
      }

      ++count;

      Future(() {
        return DummyData.rowsByColumns(length: chunkSize, columns: columns);
      }).then((value) {
        _rows.addAll(value);

        if (_rows.length == totalRows) {
          completer.complete(_rows);

          timer.cancel();
        }
      });
    });

    return completer.future;
  }

  @override
  Widget build(BuildContext context) {
    return PlutoExampleScreen(
      title: 'Add rows asynchronously',
      topTitle: 'Add rows asynchronously',
      topContents: const [
        Text(
            'The grid can freeze if there are many rows at the start of the grid.'),
        Text(
            'When a row is first set up or a new row is added, the PlutoGridStateManager.initializeRows method is executed and the necessary settings are made for the grid.'),
        Text(
            'In the example, an empty row is provided at the start of the grid, and the row is set asynchronously and reflected in the grid.'),
        Text('See the example code for details.'),
      ],
      topButtons: [
        PlutoExampleButton(
          url:
              'https://github.com/bosskmk/pluto_grid/blob/master/demo/lib/screen/feature/add_rows_asynchronously.dart',
        ),
      ],
      body: PlutoGrid(
        columns: columns,
        rows: rows,
        onChanged: (PlutoGridOnChangedEvent event) {
          print(event);
        },
        onLoaded: (PlutoGridOnLoadedEvent event) {
          stateManager = event.stateManager;

          /// When the grid is finished loading, enable loading.
          stateManager.setShowLoading(true);
        },
        configuration: const PlutoGridConfiguration(),
      ),
    );
  }
}

```

**Comment by fenchai23** [comment]
@bosskmk 

thanks for the example, once I get the time I'll definitely try it out, I am not sure how it is gonna perform because I am also applying some logic into the plutocolumn builder, it checks each cell if cell value is in a list, if it is then it will change its color, value etc depending on some logic.

this async build method looks promising.

**Comment by fenchai23** [comment]
@bosskmk 

sorry for bothering you, but I got stuck while trying to replicate your example for async build method.

in `Future<List<PlutoRow>> fetchRows() `
I am not sure how to implement this:
`return DummyData.rowsByColumns(length: chunkSize, columns: columns);
`
this is an example of my how I fetch rows:
``` Dart
List<PlutoRow> getPlutoRows() {
    List<PlutoRow> rows = [];

    csvMapList.forEach((e) {
      Map<String, PlutoCell> map = {};
      e.asMap().forEach((index, value) {
        PlutoCell p = PlutoCell();
        p = PlutoCell(value: value);
        map[index.toString()] = p;
      });
      rows.add(PlutoRow(cells: map));
    });

    return rows;
  }
```

**Comment by bosskmk** [comment]
@fenchai23 

`fetchRows` is just a function for the sake of example.
If `csvMapList` has many elements, it can be implemented using `compute` or `Isolate`.
