### ISSUE TITLE
LateInitializationError: Field '_column@1169200100' has not been initialized.

### ISSUE THREAD

**Issue by jonahzheng** [bosskmk/pluto_grid#499]
```
The following LateError was thrown during a scheduler callback:
LateInitializationError: Field '_column@1169200100' has not been initialized.

When the exception was thrown, this was the stack: 
#0      PlutoCell._column (package:pluto_grid/src/model/pluto_cell.dart)
#1      PlutoCell.column (package:pluto_grid/src/model/pluto_cell.dart:47:29)
#2      EditingState.changeCellValue (package:pluto_grid/src/manager/state/editing_state.dart:179:32)
#3      TextCellState._changeValue (package:pluto_grid/src/ui/cells/text_cell.dart:138:25)
#4      TextCellState.dispose.<anonymous closure> (package:pluto_grid/src/ui/cells/text_cell.dart:59:9)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1091:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#11     _invoke (dart:ui/hooks.dart:151:10)
#12     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#13     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
```
edit cell

```
            onChanged: (PlutoGridOnChangedEvent event) {
              log('new: '+ event.value);
              //event.cells[event.column.field]!.value.toString(),
             // print(event);
            },
```

flutter 3.0

pluto_grid:2.10.0

**Comment by bosskmk** [comment]
A `PlutoColumn` is provided first in the `PlutoGrid` constructor or must be added with the `stateManager.insertColumns` method in order for columns to be added at runtime.

Otherwise, the `PlutoCell.column` value will not be set and an error will occur.

```dart
final columns = <PlutoColumn>[
// ...columns
];
PlutoGrid(
  columns: columns,

// or

stateManager.insertColumns(0, [PltuoColumn(), PlutoColumn()]);
```

If this answer did not solve the problem, I would appreciate it if you could provide a minimal code that can reproduce the error.

**Comment by FloRul** [comment]
Had the same problem, figured it was related to the grid mode. Issue happens when the grid mode is PlutoGridMode.select and PlutoGridMode.selectWithOneTap as well.

**Comment by bosskmk** [comment]
@FloRul 
Can you provide minimal sample code to reproduce the error?

**Comment by bosskmk** [comment]
@FloRul 

In your code, you are specifying a field in a column that does not exist in Row.

It seems that PlutoGrid should display the correct error message for the error.



```dart
rows: [
  PlutoRow(
    key: UniqueKey(),
    cells: {
      // This field id is not specfic in columns
      'id': PlutoCell(value: 2),
      'quotaNumber': PlutoCell(value: 'quotaNumber'),
      'vendorNumber': PlutoCell(value: 'vendorNumber'),
      'name': PlutoCell(value: 'companyName'),
      'origin': PlutoCell(value: 'origin.code'),
      'cycleType': PlutoCell(value: 'origin'),
      'cycleTolerance': PlutoCell(value: 'cycleTolerance'),
      'henhousesCount': PlutoCell(value: 'henhousesCount'),
      'city': PlutoCell(value: 'city'),
      'phone1': PlutoCell(value: 'phone1'),
      'phone2': PlutoCell(value: 'phone2'),
      'totalCapacity': PlutoCell(value: 'henhousesTotalCapacity'),
      'isActive': PlutoCell(value: 'active'),
    },
  ),
],
```

**Comment by bosskmk** [comment]
Added to the document how to add or remove columns and rows after setting them.

https://pluto.weblaze.dev/add-and-remove-columns-and-rows

**Comment by jonahzheng** [comment]
@bosskmk thank you for you raplay,
this error is occur, because I use getx with pluto_gird, it doesn't seem to work correctly.
now I use this code to update pluto_grid
```
      gridStateManager?.removeAllRows();
      gridStateManager?.prependRows(rows);
```
