### ISSUE TITLE
[Bug] Regression from +5.0.4 - MouseTracker (blocker for development)

### ISSUE THREAD

**Issue by henry2man** [bosskmk/pluto_grid#613]
I've found a regression. In my project (MacOS & Web) I was using `5.0.3` version. Upgrading to `+5.0.4` breaks the whole project, causing mouse related issues that freezes the whole app.

I've created a minimal example.

### Steps to reproduce the bug
1. Download and run attached demo code.
2. Navigate to "Test2" tab.
3. The app freezes and logs shows MouseTracker related errors
4. Change `pluto_grid` dependency to `5.0.3`
5. Restart the app. Use the app and MouseTracker errors are gone.

### Expected results
Run the example without issues.

### Actual results

```dart
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 205 pos 12: '!_debugDuringDeviceUpdate': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:205:12)
#3      MouseTracker.updateAllDevices (package:flutter/src/rendering/mouse_tracker.dart:366:5)
#4      RendererBinding._scheduleMouseTrackerUpdate.<anonymous closure> (package:flutter/src/rendering/binding.dart:395:22)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#8      _invoke (dart:ui/hooks.dart:148:13)
#9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#10     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 205 pos 12: '!_debugDuringDeviceUpdate': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:205:12)
#3      MouseTracker.updateWithEvent.<anonymous closure> (package:flutter/src/rendering/mouse_tracker.dart:322:7)
#4      MouseTracker._monitorMouseConnection (package:flutter/src/rendering/mouse_tracker.dart:193:9)
#5      MouseTracker.updateWithEvent (package:flutter/src/rendering/mouse_tracker.dart:321:5)
#6      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:20)
#7      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#8      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#9      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#10     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#11     _invoke1 (dart:ui/hooks.dart:167:13)
#12     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#13     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)```

### Code sample

[demo-bug-mouse-5.0.4plus.zip](https://github.com/bosskmk/pluto_grid/files/9850846/demo-bug-mouse-5.0.4plus.zip)

### Execution Environment
**Flutter version**
Flutter version is 3.3.5 (stable)

**PlutoGrid version**
PlutoGrid version is 5.0.3 - 5.0.4

**OS**
MacOS 12.6 Monterrey

**Comment by henry2man** [comment]
I've cross posted this in https://github.com/bdlukaa/fluent_ui/issues/590 because the demo uses it, too.

**Comment by bosskmk** [comment]
In the example code, an assert error occurs not only when moving tabs but also when changing column width.

Changing the setLayout method in layout_state.dart as below solves the problem, but I think we need to look further to find out the root cause.

https://github.com/bosskmk/pluto_grid/blob/master/lib/src/manager/state/layout_state.dart
```dart
  void setLayout(BoxConstraints size) {
    final previousMaxWidth = maxWidth;
    final showFrozenColumn = shouldShowFrozenColumns(size.maxWidth);
    final bool changedShowFrozenColumn = showFrozenColumn != showFrozenColumn;
    final bool changedMaxWidth = maxWidth != size.maxWidth;

    _state._maxWidth = size.maxWidth;
    _state._maxHeight = size.maxHeight;
    _state._showFrozenColumn = showFrozenColumn;
    _state._gridGlobalOffset = null;

    if (changedShowFrozenColumn || changedMaxWidth) {
      updateVisibilityLayout();

      if (previousMaxWidth != null) {
        WidgetsBinding.instance.scheduleTask(
          () => notifyResizingListeners(),
          Priority.touch,
        );
      }
    }

    if (enableColumnsAutoSize && !activatedColumnsAutoSize) {
      activateColumnsAutoSize();
    }
  }
```

**Comment by bosskmk** [comment]
Note that this is a problem that only occurs in debug mode.
