### ISSUE TITLE
[Bug] FixedScrollMetrics build issue

### ISSUE THREAD

**Issue by jeffrey-flo** [bosskmk/pluto_grid#823]
### Steps to reproduce the bug

1. flutter build 

### Actual results

```
#21 16.47 Target dart2js failed: Exception: /root/.pub-cache/hosted/pub.dev/pluto_grid-6.0.4/lib/src/widgets/pluto_scrollbar.dart:493:39:
#21 16.47 Error: Required named parameter 'devicePixelRatio' must be provided.
#21 16.47           metrics = FixedScrollMetrics(
#21 16.47                                       ^
#21 16.47 /usr/local/flutter/packages/flutter/lib/src/widgets/scroll_metrics.dart:140:3:
#21 16.47 Info: Found this candidate, but the arguments don't match.
#21 16.47   FixedScrollMetrics({
#21 16.47   ^^^^^^^^^^^^^^^^^^
#21 16.47 /root/.pub-cache/hosted/pub.dev/pluto_grid-6.0.4/lib/src/widgets/pluto_scrollbar.dart:511:39:
#21 16.47 Error: Required named parameter 'devicePixelRatio' must be provided.
#21 16.47           metrics = FixedScrollMetrics(
#21 16.47                                       ^
#21 16.47 /usr/local/flutter/packages/flutter/lib/src/widgets/scroll_metrics.dart:140:3:
#21 16.47 Info: Found this candidate, but the arguments don't match.
#21 16.47   FixedScrollMetrics({
#21 16.47   ^^^^^^^^^^^^^^^^^^
#21 16.47 Error: Compilation failed.
```

### Code sample
```dart
/// If you have a code sample here, please attach it.
```

### Execution Environment
**Flutter version**

- Flutter version 3.10.0-1.3.pre on channel beta

**PlutoGrid version**

PlutoGrid version is 6.0.4

**OS**

**Comment by Miranda-dev** [comment]
Hi I added devicePixelRatio: 1.0 on every line with error and that solved this error. I read in the latest version of Flutter devicePixelRatio is required
