### ISSUE TITLE
Unhandled Exception in _PlutoLazyPaginationState.setPage

### ISSUE THREAD

**Issue by s-yanev** [bosskmk/pluto_grid#829]
**Describe the bug**
An unhandled exception occurs when navigating to another page while `PlutoLazyPagination` widget is still processing an async request :

```
Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 170 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      ScrollController.jumpTo (package:flutter/src/widgets/scroll_controller.dart:170:12)
#3      _PlutoLazyPaginationState.setPage.<anonymous closure> (package:pluto_grid/src/plugin/pluto_lazy_pagination.dart:183:45)
<asynchronous suspension>
```

**To Reproduce**

1. Create a `PlutoGrid` with a `PlutoLazyPagination` widget in it.
2. Mock the fetch request to some long operation, for example: 
 ```
 await Future.delayed(const Duration(seconds: 5));
 ```
3. While the async operation is working try to navigate to some other screen.

**Expected behavior**
Check if the `ScrollController` is actually attached to a view before attempting to do the `jumpTo()` action.

**Additional context**
The place where the exception happens is in the `pluto_lazy_pagination.dart` file, at the `setPage()` function, line 183 :
```
void setPage(int page) async {
    if (_isFetching) return;

    _isFetching = true;

    stateManager.setShowLoading(true, level: PlutoGridLoadingLevel.rows);

    widget
        .fetch(
      PlutoLazyPaginationRequest(
        page: page,
        sortColumn: stateManager.getSortedColumn,
        filterRows: stateManager.filterRows,
      ),
    )
        .then((data) {
      stateManager.scroll.bodyRowsVertical!.jumpTo(0); // <-- Unhandled Exception here

      stateManager.refRows.clearFromOriginal();
      stateManager.insertRows(0, data.rows);

      setState(() {
        _page = page;

        _totalPage = data.totalPage;

        _isFetching = false;
      });

      stateManager.setShowLoading(false);
    });
  }
``` 
It seems that when the async operation is invoked, there is a possibility that when the `then()` callback is called the `PlutoGrid` to be already removed from the screen. 

One possible solution for resolving the issue can be to just check if the widget is still mounted. Something like this:
```
if(mounted) {
            stateManager.scroll.bodyRowsVertical!.jumpTo(0);

            stateManager.refRows.clearFromOriginal();
            stateManager.insertRows(0, data.rows);

            setState(() {
              _page = page;

              _totalPage = data.totalPage;

              _isFetching = false;
            });

            stateManager.setShowLoading(false);
          }
```

**Comment by s-yanev** [comment]
Issue is fixed with PR - #830
